services:
  db:
    image: mysql:latest
    container_name: MYSQL
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=appdb
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: