services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=appdb
    ports:
      - 3007:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
 mysql_data: